/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pdfgen;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Element;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import java.text.SimpleDateFormat;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class PDForm extends javax.swing.JFrame {

    /**
     * Creates new form PDForm
     */
    public PDForm() {
        initComponents();
        setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_fecha = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_direccion = new javax.swing.JLabel();
        lbl_formapago = new javax.swing.JLabel();
        lbl_vendedor = new javax.swing.JLabel();
        lbl_cp = new javax.swing.JLabel();
        lbl_tel = new javax.swing.JLabel();
        lbl_tipoenvio = new javax.swing.JLabel();
        lbl_cuenta = new javax.swing.JLabel();
        btn_imprimir = new javax.swing.JButton();
        txt_vendedor = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_cp = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        box_formapago = new javax.swing.JComboBox<>();
        txt_tipoenvio = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_cuenta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        btn_agregar = new javax.swing.JButton();
        lbl_cantidad = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_descripcion = new javax.swing.JLabel();
        txt_descripcion = new javax.swing.JTextField();
        lbl_precio = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_reex = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        txt_enviop = new javax.swing.JTextField();
        txt_reex = new javax.swing.JTextField();
        lbl_result = new javax.swing.JLabel();
        spin_Cantidad = new javax.swing.JSpinner();
        spin_Precio = new javax.swing.JSpinner();
        fecha = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("PDFrame"); // NOI18N
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NOTAS DE VENTA");

        lbl_fecha.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        lbl_fecha.setText("Fecha:");

        lbl_nombre.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        lbl_nombre.setText("Nombre:");

        lbl_direccion.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        lbl_direccion.setText("Dirección:");

        lbl_formapago.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        lbl_formapago.setText("Forma de pago:");

        lbl_vendedor.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        lbl_vendedor.setText("Vendedor:");

        lbl_cp.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        lbl_cp.setText("Código postal:");

        lbl_tel.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        lbl_tel.setText("Tel.");

        lbl_tipoenvio.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        lbl_tipoenvio.setText("Tipo de envío:");

        lbl_cuenta.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        lbl_cuenta.setText("Cuenta:");

        btn_imprimir.setBackground(new java.awt.Color(255, 255, 255));
        btn_imprimir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_imprimir.setText("Imprimir");
        btn_imprimir.setFocusPainted(false);
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });

        txt_vendedor.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        txt_nombre.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        txt_cp.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        txt_direccion.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        box_formapago.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        box_formapago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta de crédito" }));

        txt_tipoenvio.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        txt_telefono.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        txt_cuenta.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Descripción", "Precio", "Importe"
            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        btn_agregar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        lbl_cantidad.setText("Cantidad:");

        lbl_descripcion.setText("Descripción:");

        lbl_precio.setText("Precio:");

        jLabel2.setText("ENVIO:");

        lbl_reex.setText("REEX:");

        lbl_total.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_total.setForeground(new java.awt.Color(255, 0, 0));
        lbl_total.setText("TOTAL");

        lbl_result.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_result.setForeground(new java.awt.Color(255, 0, 0));

        spin_Cantidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spin_Precio.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(309, 309, 309))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(spin_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)
                                        .addComponent(lbl_descripcion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbl_cantidad))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_precio)
                                .addGap(18, 18, 18)
                                .addComponent(spin_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_formapago)
                                .addGap(18, 18, 18)
                                .addComponent(box_formapago, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(lbl_cuenta)
                                .addGap(18, 18, 18)
                                .addComponent(txt_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_nombre)
                                    .addComponent(lbl_direccion))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(142, 142, 142)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbl_fecha)
                                                .addGap(18, 18, 18)
                                                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(39, 39, 39))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbl_vendedor)
                                                .addGap(18, 18, 18)
                                                .addComponent(txt_vendedor))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(lbl_cp)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_cp, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbl_tipoenvio)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txt_tipoenvio, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbl_tel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_reex)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_agregar)
                                .addGap(42, 42, 42)
                                .addComponent(btn_imprimir)
                                .addGap(101, 101, 101)
                                .addComponent(lbl_total)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_enviop, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(txt_reex, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(lbl_result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_fecha)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_vendedor)
                                    .addComponent(txt_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_cp)
                                    .addComponent(txt_cp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_tel)
                                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_formapago)
                                    .addComponent(box_formapago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_cuenta)
                                    .addComponent(txt_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_tipoenvio)
                                    .addComponent(txt_tipoenvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_descripcion)
                                    .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_precio)
                                    .addComponent(spin_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_nombre)
                                .addGap(36, 36, 36)
                                .addComponent(lbl_direccion)
                                .addGap(128, 128, 128)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_cantidad)
                                    .addComponent(spin_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(txt_enviop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_reex)
                            .addComponent(txt_reex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_total)
                                .addComponent(lbl_result, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_imprimir))))
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirActionPerformed
        crearPDF();
    }//GEN-LAST:event_btn_imprimirActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
         
        DefaultTableModel modelo = (DefaultTableModel) tblDatos.getModel();

        int importe = ((Integer)spin_Cantidad.getValue() * (Integer)spin_Precio.getValue());

        Object [] fila=new Object[4];

        fila[0]=spin_Cantidad.getValue();  
        fila[1]=txt_descripcion.getText(); 
        fila[2]=spin_Precio.getValue(); 
        fila[3]=importe;

        modelo.addRow(fila);
        tblDatos.setModel(modelo);

        int costoEnvio = Integer.valueOf(txt_enviop.getText());
        int reex = Integer.valueOf(txt_reex.getText());

        int costoTotal = ( importe + costoEnvio + reex);
        lbl_result.setText(String.valueOf(costoTotal));

    }//GEN-LAST:event_btn_agregarActionPerformed
    


        /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
         /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PDForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PDForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PDForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PDForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PDForm().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box_formapago;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_imprimir;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_cantidad;
    private javax.swing.JLabel lbl_cp;
    private javax.swing.JLabel lbl_cuenta;
    private javax.swing.JLabel lbl_descripcion;
    private javax.swing.JLabel lbl_direccion;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_formapago;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_precio;
    private javax.swing.JLabel lbl_reex;
    private javax.swing.JLabel lbl_result;
    private javax.swing.JLabel lbl_tel;
    private javax.swing.JLabel lbl_tipoenvio;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JLabel lbl_vendedor;
    private javax.swing.JSpinner spin_Cantidad;
    private javax.swing.JSpinner spin_Precio;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txt_cp;
    private javax.swing.JTextField txt_cuenta;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_enviop;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_reex;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txt_tipoenvio;
    private javax.swing.JTextField txt_vendedor;
    // End of variables declaration//GEN-END:variables

    private void crearPDF() {
 
        Document document = new Document();
 
        try {

            JFileChooser selectorRuta = new JFileChooser();
            int botonClickeado = selectorRuta.showOpenDialog(this);
            if( botonClickeado == JFileChooser.APPROVE_OPTION){
                selectorRuta.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                File archivo = selectorRuta.getSelectedFile();
                PdfWriter.getInstance(document, new FileOutputStream(archivo));

                document.open();

                Paragraph paragraphHello = new Paragraph();
                paragraphHello.add("REBERZZA");
                paragraphHello.setAlignment(Element.ALIGN_JUSTIFIED);

                document.add(paragraphHello);
                document.add(Chunk.NEWLINE);
                document.add(Chunk.NEWLINE);

                Phrase line1 = new Phrase();
                Phrase line2 = new Phrase();
                Phrase line3 = new Phrase();
                Phrase line4 = new Phrase();
                Phrase line5 = new Phrase();
                Phrase line6 = new Phrase();
                Phrase line7 = new Phrase();
                Phrase line8 = new Phrase();

                //Damos formato a la fecha
                SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
                String Fecha = formato.format(fecha.getDate());

                line1.add("Nombre: "  + txt_nombre.getText()+"        ");
                line1.add("Fecha: "  + Fecha);
                line2.add("Vendedor: "  + txt_vendedor.getText());
                line3.add("Dirección: "  + txt_direccion.getText()+" ");
                line3.add("Forma de Pago: "  + box_formapago.getSelectedItem());
                line4.add("C.P.: "  + txt_cp.getText());
                line4.add("Cuenta: "  + txt_cuenta.getText()+" ");
                line5.add("Tel: "  + txt_telefono.getText()+" ");
                line5.add("Tipo de envio: "  + txt_tipoenvio.getText());

                document.add(line1);
                document.add(Chunk.NEWLINE);
                document.add(line2);
                document.add(Chunk.NEWLINE);
                document.add(line3);
                document.add(Chunk.NEWLINE);
                document.add(line4);
                document.add(Chunk.NEWLINE);
                document.add(line5);
                document.add(Chunk.NEWLINE);
                document.add(line6);
                document.add(Chunk.NEWLINE);
                document.add(line7);
                document.add(Chunk.NEWLINE);
                document.add(line8);

                // Creating a table         
                PdfPTable table = new PdfPTable(4);
                table.setWidths(new int[]{ 1, 2, 1, 1});
                table.setSpacingBefore(0f);
                table.setSpacingAfter(0f);
                table.setHorizontalAlignment(0);

                // Cabecera de la tabla
                table.addCell("Cantidad");
                table.addCell("Descripcion");
                table.addCell("Precio");
                table.addCell("Importe");

                //Datos de la tabla
                for(int i=0;i<tblDatos.getRowCount();i++){
                    for(int z=0;z < tblDatos.getColumnCount();z++){
                        table.addCell((PdfPCell) tblDatos.getValueAt(i,z));
                    }
                }


                int can = (Integer)spin_Cantidad.getValue();
                int pre = (Integer)spin_Precio.getValue();

                int importe = (can * pre);

                String importe2 = String.valueOf(importe);

                table.addCell(new Phrase(importe2));

                PdfPTable table2 = new PdfPTable(2);
                table2.setWidths(new int[]{1, 1});
                table2.setWidthPercentage(30);
                table2.setSpacingBefore(0f);
                table2.setSpacingAfter(0f);
                table2.setHorizontalAlignment(0);

                int enviof = Integer.valueOf(txt_enviop.getText());
                int reex = Integer.valueOf(txt_reex.getText());

                int total = (importe+enviof+reex);
                String total2 = String.valueOf(total);

                // first row
                table2.addCell("ENVIO");
                table2.addCell(txt_enviop.getText());
                table2.addCell("REEX");
                table2.addCell(txt_reex.getText());
                table2.addCell("TOTAL");
                table2.addCell(new Phrase(total2));

                document.add(table);
                document.add(Chunk.NEWLINE);
                document.add(table2);

                document.close();
            }else if( botonClickeado == JFileChooser.CANCEL_OPTION){
                JOptionPane.showMessageDialog(null, "Se canceló el proceso");
            }
            
        } catch (FileNotFoundException | DocumentException e) {
            e.printStackTrace();
        }
    }
}
